### ISSUE TITLE
Where to get this ansible_distribution?

### ISSUE THREAD

**Issue by kennyth01** [robertdebock/ansible-role-epel#1]
**Describe the bug**
Hi, I hit this ansible_distribution is undefined error.

**Playbook**

```yaml
---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  roles:
     - robertdebock.epel
```

**Output**
 FAILED! => {"msg": "The conditional check 'ansible_distribution in [ \"CentOS\", \"RedHat\", \"Amazon\" ]' failed. The error was: error while evaluating conditional (ansible_distribution in [ \"CentOS\", \"RedHat\", \"Amazon\" ]): 'ansible_distribution' is undefined\n\nThe error appears to be in '/Users/xxx/.ansible/roles/robertdebock.epel/tasks/main.yml': line 3, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# tasks file for epel\n- name: install epel-release\n  ^ here\n"}

**Expected behavior**
To run smoothly

**Environment**
- Control Node: Mac OS
- ansible 2.9.3
- Manage Node: CentOS 8

**Comment by kennyth01** [comment]
Figured it out. I got to include your bootstrap role too. Thanks for this.

**Comment by robertdebock** [comment]
Hi,

The variables `ansible_*` variables are [facts](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variables-discovered-from-systems-facts), you can set `gather_facts` to `yes`:

```yaml
---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes
  roles:
     - robertdebock.epel
```
